
language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt

script:
  - echo "no scripts"

after_success:
  #- bash <(curl -s https://scripts.scantist.com/staging/ci-travis-jar.sh)
  - npm install -g snyk
  - snyk -v
  - snyk auth $SNYK_TOKEN
  - snyk monitor
